use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "superKEY987654321!!"
  limiter: false
  public_instance: false

search:
  default_lang: "en"
  safe_search: 0
  autocomplete: "google"

engines:
  # The list item '-' should be indented by two spaces under 'engines'.
  # 'name' and 'engine' should be indented by two more spaces (four total).
  - name: dummy
    engine: dummy